from base_load import base_load
from boiler import boiler
from coffee_machine import coffee_machine
from dish_washer import dish_washer
from freezer import freezer
from fridge import fridge
from hair_dryer import hair_dryer
from hifi import hifi
from ict import ict
from iron import iron
from kettle import kettle
from lighting import lighting
from microwave import microwave
from oven import oven
from stove import stove
from toaster import toaster
from tumble_dryer import tumble_dryer
from tv import tv
from vacuum_cleaner import vacuum_cleaner
from washing_machine import washing_machine